### PR TITLE
fixes issue #39

### PR DESCRIPTION
**Pull request by tomarcafe**

### CODE REVIEW

**Comment by DarthVanger** [comment]
It fixes issue https://github.com/DarthVanger/NeuralNotes/issues/39, not 43 :)
Please correct the commit message to mention the correct issue number.
Well done! Thanks!
Are you coming from the Ethlance job posting?

**Comment by tomarcafe** [comment]
> It fixes issue #39, not #43 :)
for me, it fixes #43 as well :)
> Please correct the commit message to mention the correct issue number.
will do
> Are you coming from the Ethlance job posting?
yes.

**Comment by DarthVanger** [comment]
You're right, it fixes #43 as well :) my bad

**Comment by DarthVanger** [comment]
@tomarcafe so, do you want to apply for the job? :)

Where can we talk, email/telegram/here? :)

**Comment by tomarcafe** [comment]
> @tomarcafe so, do you want to apply for the job? :)

still thinking about it. seems hard :)
 
> Where can we talk, email/telegram/here? :)

**Pull request merged**
